# The Directories, Source, Includes, Objects, Binary 
UTIL_DIR := util

# Sources
UTIL_SRC := $(UTIL_DIR)/logger.cpp

create-folders::
	@mkdir -p $(BUILD_DIR)/$(UTIL_DIR)

# Objects
UTIL_OBJ=$(addprefix $(BUILD_DIR)/, $(UTIL_SRC:.cpp=.o))
