# Directories
UTIL_DIR := util

# Sources
UTIL_SRC := $(UTIL_DIR)/logger.cpp

# Objects
UTIL_OBJ := $(addprefix $(BUILD_DIR)/, $(UTIL_SRC:.cpp=.o))

# Build folders
create-folders::
	@mkdir -p $(BUILD_DIR)/$(UTIL_DIR)
