# Directories
AST_DIR := ast

# Sources
AST_SRC := $(AST_DIR)/sbg_program.cpp \
	$(AST_DIR)/statement.cpp \
	$(AST_DIR)/expr.cpp

# Objects
AST_OBJ := $(addprefix $(BUILD_DIR)/, $(AST_SRC:.cpp=.o))

# Build folders
create-folders::
	@mkdir -p $(BUILD_DIR)/$(AST_DIR)
