# Directories
PARSER_DIR  := parser

# Sources
PARSER_SRC := \
	$(PARSER_DIR)/parser.cpp \
	$(PARSER_DIR)/statement.cpp \
	$(PARSER_DIR)/expr.cpp \
	$(PARSER_DIR)/sbg_program.cpp \
	$(PARSER_DIR)/skipper.cpp

# Objects
PARSER_OBJ = $(addprefix $(BUILD_DIR)/, $(PARSER_SRC:.cpp=.o))

# Binary
PARSER_BIN := $(BIN_DIR)/sbg-parser

# Binary compilation
PARSER_BIN_FLAGS := -Llib/ -lsbgraph 

# Build folders
create-folders::
	@mkdir -p $(BUILD_DIR)/$(PARSER_DIR)

# Binary compilation
$(PARSER_BIN): $(LIB_SBGRAPH)
	$(CXX) $(CXXFLAGS) -o $(PARSER_BIN) $(INCLUDES) $(PARSER_DIR)/main.cpp \
  $(PARSER_BIN_FLAGS)
