# Directories
ALG_DIR := algorithms/partitioner

# Build folders
create-folders::
	@mkdir -p $(BUILD_DIR)/$(ALG_DIR)

# Sources
ALG_SRC := \
  $(ALG_DIR)/weighted_sb_graph.cpp \
  $(ALG_DIR)/build_sb_graph.cpp

# Objects
ALG_OBJ=$(addprefix $(BUILD_DIR)/, $(ALG_SRC:.cpp=.o))

# Compilation
$(BUILD_DIR)/%.o: %.cpp | create-folders
	$(CC) $(INCLUDES) $(CXXFLAGS) -MM -MT $@ -MF $(patsubst %.o,%.d,$@) $<
	$(CC) $(INCLUDES) -c $< -o $@ $(CXXFLAGS)

# Binary
SBG_PARTITIONER := bin/sbg-partitioner

# Binary compilation
PARTITIONER_FLAGS := $(CXXFLAGS) -Llib/ -lsbgraph -lstdc++ -lm

$(SBG_PARTITIONER): $(LIB_SBGRAPH)
	$(CXX) -o $(SBG_PARTITIONER) $(INCLUDES) $(ALG_DIR)/main.cpp $(PARTITIONER_FLAGS)

all: $(SBG_PARTITIONER)
