# The Directories, Source, Includes, Objects, Binary 
ALG_DIR := algorithms/partitioner
SBG_PARTITIONER := bin/sbg-partitioner
PARTITIONER_FLAGS := $(CXXFLAGS) -Llib/ -lsbgraph -lstdc++ -lm


all: $(SBG_PARTITIONER)

# Sources
ALG_SRC := \
  $(ALG_DIR)/weighted_sb_graph.cpp \
  $(ALG_DIR)/build_sb_graph.cpp

create-folders::
	@mkdir -p $(BUILD_DIR)/$(ALG_DIR)

# Objects
ALG_OBJ=$(addprefix $(BUILD_DIR)/, $(ALG_SRC:.cpp=.o))


$(SBG_PARTITIONER): $(ALG_OBJ) $(LIB_SBGRAPH)
	$(CXX) -o $(SBG_PARTITIONER) $(INCLUDES) $(ALG_DIR)/main.cpp $(PARTITIONER_FLAGS)