# Directories
PARTITIONER_DIR := algorithms/partitioner

# Sources
PARTITIONER_SRC := \
  $(PARTITIONER_DIR)/build_sb_graph.cpp \
  $(PARTITIONER_DIR)/cost.cpp \
  $(PARTITIONER_DIR)/dfs_on_sbg.cpp \
  $(PARTITIONER_DIR)/kernighan_lin_partitioner.cpp \
  $(PARTITIONER_DIR)/partition_graph.cpp \
  $(PARTITIONER_DIR)/partition_metrics_api.cpp \
  $(PARTITIONER_DIR)/partition_strategy.cpp \
  $(PARTITIONER_DIR)/weighted_sb_graph.cpp
ALG_SRC += $(PARTITIONER_SRC)

# Objects
ALG_OBJ += $(addprefix $(BUILD_DIR)/, $(PARTITIONER_SRC:.cpp=.o))

# Binary
PARTITIONER_BIN := bin/sbg-partitioner

# Binary flags
PARTITIONER_FLAGS := $(CXXFLAGS) -Llib/ -lsbgraph -lstdc++ -lm

# Build folders
create-folders::
	@mkdir -p $(BUILD_DIR)/$(PARTITIONER_DIR)

# Binary compilation
$(PARTITIONER_BIN): $(LIB_SBGRAPH)
	$(CXX) -o $(PARTITIONER_BIN) $(INCLUDES) $(PARTITIONER_DIR)/main.cpp \
  $(PARTITIONER_FLAGS)
