# Directories
TEARING_DIR := algorithms/tearing

# Sources
TEARING_SRC := $(TEARING_DIR)/tearing.cpp
ALG_SRC += $(TEARING_SRC)

# Objects
ALG_OBJ += $(addprefix $(BUILD_DIR)/, $(TEARING_SRC:.cpp=.o))

# Build folders
create-folders::
	@mkdir -p $(BUILD_DIR)/$(TEARING_DIR)