#!/usr/bin/env python3

import subprocess

def get_files():
    files = subprocess.check_output(['git', 'diff-index','--cached',
                                    '--name-only', 'HEAD']).split()
    files = filter(lambda x: x.find('sbg/test/stest/gt_data') == -1, files)

    files = filter(lambda x: x.endswith('.c') or
                             x.endswith('.h') or
                             x.endswith('.cpp'), files)
    return files

def apply_code_style():
    files = get_files()
    for f in files:
      print("Apply code style to: " + f)
      subprocess.check_output(['clang-format-7', '-i', f])
      subprocess.check_output(['git', 'add', f])

def apply_cpp_clean():
    files = get_files()
    for f in files:
        try:
            out = subprocess.check_output(['cppclean', '-I', './sbg/', f])                       
        except subprocess.CalledProcessError as ret:                                                                                                   
            print ('cppclean error in file {}:\n'.format(f))
            for c in ret.output.split('\n'):
                print(c)
            print ('Apply the suggested changes.\n'
                   'Then re-stage the changes and redo commit.\n')

def main():
    apply_code_style()
    apply_cpp_clean()

if (__name__ == '__main__'):
    main()