# The Directories, Source, Includes, Objects, Binary 
UTIL_ROOT := util
SBG_ROOT := sbg

# Sources
	SBG_SRC := \
    $(UTIL_ROOT)/defs.cpp \
  	$(SBG_ROOT)/interval.cpp \
    $(SBG_ROOT)/pw_inter.cpp \
    $(SBG_ROOT)/lexp.cpp \
    $(SBG_ROOT)/map.cpp

# Objects
SBG_OBJ=$(addprefix $(BUILD_DIR)/, $(SBG_SRC:.cpp=.o))

create-folders::
	@mkdir -p $(BUILD_DIR)/$(SBG_ROOT)
