# The Directories, Source, Includes, Objects, Binary 
SBG_DIR         := sbg
PARSER_DIR      := parser
TEST_DIR        := sbg/test
UTEST_DIR       := $(TEST_DIR)/utest
STEST_DIR       := $(TEST_DIR)/stest
GRP_TEST        := $(UTEST_DIR)/graph-test
MTCHNG_TEST     := $(UTEST_DIR)/matching-test
SCC_TEST        := $(UTEST_DIR)/scc-test
ORDER_TEST      := $(UTEST_DIR)/order-test
SBG_GRAPH_TEST  := test-sbg-graph

all: $(GRP_TEST) $(MTCHNG_TEST) $(SCC_TEST) $(ORDER_TEST)

GRP_TEST_SRC := \
    $(UTEST_DIR)/graph_test.cpp \
    $(SBG_DIR)/util/defs.cpp \
    $(SBG_DIR)/util/logger.cpp \
    $(SBG_DIR)/interval.cpp \
    $(SBG_DIR)/multi_interval.cpp \
    $(SBG_DIR)/set.cpp \
    $(SBG_DIR)/lmap.cpp \
    $(SBG_DIR)/atom_pw_map.cpp \
    $(SBG_DIR)/pw_map.cpp \
    $(SBG_DIR)/descs.cpp \
    $(SBG_DIR)/sbg.cpp \
    $(SBG_DIR)/atom_sbg.cpp \
    $(SBG_DIR)/sbg_algorithms.cpp \
    $(SBG_DIR)/sbg_io.cpp \
    $(SBG_DIR)/converter_io.cpp \
    $(SBG_DIR)/graph_builders/scc_graph_builder.cpp \
    $(SBG_DIR)/sbg_printer.cpp 

MTCHNG_TEST_SRC := \
    $(UTEST_DIR)/matching_test.cpp \
    $(PARSER_DIR)/converter.cpp \
    $(PARSER_DIR)/parser.cpp \
    $(PARSER_DIR)/compact_parser.cpp \
    $(PARSER_DIR)/comp_converter.cpp \
    $(SBG_DIR)/util/defs.cpp \
    $(SBG_DIR)/util/logger.cpp \
    $(SBG_DIR)/interval.cpp \
    $(SBG_DIR)/multi_interval.cpp \
    $(SBG_DIR)/set.cpp \
    $(SBG_DIR)/lmap.cpp \
    $(SBG_DIR)/atom_pw_map.cpp \
    $(SBG_DIR)/pw_map.cpp \
    $(SBG_DIR)/descs.cpp \
    $(SBG_DIR)/sbg.cpp \
    $(SBG_DIR)/atom_sbg.cpp \
    $(SBG_DIR)/sbg_printer.cpp \
    $(SBG_DIR)/sbg_algorithms.cpp \
    $(SBG_DIR)/sbg_io.cpp \
    $(SBG_DIR)/converter_io.cpp

SCC_TEST_SRC := \
    $(UTEST_DIR)/scc_test.cpp \
    $(PARSER_DIR)/converter.cpp \
    $(PARSER_DIR)/parser.cpp \
    $(PARSER_DIR)/compact_parser.cpp \
    $(PARSER_DIR)/comp_converter.cpp \
    $(SBG_DIR)/util/defs.cpp \
    $(SBG_DIR)/util/logger.cpp \
    $(SBG_DIR)/interval.cpp \
    $(SBG_DIR)/multi_interval.cpp \
    $(SBG_DIR)/set.cpp \
    $(SBG_DIR)/lmap.cpp \
    $(SBG_DIR)/atom_pw_map.cpp \
    $(SBG_DIR)/pw_map.cpp \
    $(SBG_DIR)/descs.cpp \
    $(SBG_DIR)/sbg.cpp \
    $(SBG_DIR)/atom_sbg.cpp \
    $(SBG_DIR)/sbg_printer.cpp \
    $(SBG_DIR)/sbg_algorithms.cpp \
    $(SBG_DIR)/sbg_io.cpp \
    $(SBG_DIR)/converter_io.cpp \
    $(SBG_DIR)/graph_builders/scc_graph_builder.cpp

ORDER_TEST_SRC := \
    $(UTEST_DIR)/order_test.cpp \
    $(PARSER_DIR)/converter.cpp \
    $(PARSER_DIR)/parser.cpp \
    $(PARSER_DIR)/compact_parser.cpp \
    $(PARSER_DIR)/comp_converter.cpp \
    $(SBG_DIR)/util/defs.cpp \
    $(SBG_DIR)/util/logger.cpp \
    $(SBG_DIR)/interval.cpp \
    $(SBG_DIR)/multi_interval.cpp \
    $(SBG_DIR)/set.cpp \
    $(SBG_DIR)/lmap.cpp \
    $(SBG_DIR)/atom_pw_map.cpp \
    $(SBG_DIR)/pw_map.cpp \
    $(SBG_DIR)/descs.cpp \
    $(SBG_DIR)/sbg.cpp \
    $(SBG_DIR)/atom_sbg.cpp \
    $(SBG_DIR)/sbg_printer.cpp \
    $(SBG_DIR)/sbg_algorithms.cpp \
    $(SBG_DIR)/sbg_io.cpp \
    $(SBG_DIR)/converter_io.cpp \
    $(SBG_DIR)/graph_builders/order_graph_builder.cpp

# Objects
GRP_TEST_OBJ=$(addprefix $(BUILD_DIR)/, $(GRP_TEST_SRC:.cpp=.o))

MTCHNG_TEST_OBJ=$(addprefix $(BUILD_DIR)/, $(MTCHNG_TEST_SRC:.cpp=.o))

SCC_TEST_OBJ=$(addprefix $(BUILD_DIR)/, $(SCC_TEST_SRC:.cpp=.o))

ORDER_TEST_OBJ=$(addprefix $(BUILD_DIR)/, $(ORDER_TEST_SRC:.cpp=.o))

create-folders::
	@mkdir -p $(BUILD_DIR)/sbg/test
	@mkdir -p $(BUILD_DIR)/sbg/test/utest
	@mkdir -p $(BUILD_DIR)/sbg/test/stest

$(GRP_TEST): $(GRP_TEST_OBJ)
	$(CXX) $(INCLUDES) $(CXXFLAGS) -o $(GRP_TEST) $(GRP_TEST_OBJ) $(LIBS)

$(MTCHNG_TEST): $(MTCHNG_TEST_OBJ)
	$(CXX) $(INCLUDES) $(CXXFLAGS) -o $(MTCHNG_TEST) $(MTCHNG_TEST_OBJ) $(LIBS)

$(SCC_TEST): $(SCC_TEST_OBJ)
	$(CXX) $(INCLUDES) $(CXXFLAGS) -o $(SCC_TEST) $(SCC_TEST_OBJ) $(LIBS)

$(ORDER_TEST): $(ORDER_TEST_OBJ)
	$(CXX) $(INCLUDES) $(CXXFLAGS) -o $(ORDER_TEST) $(ORDER_TEST_OBJ) $(LIBS)

$(SBG_GRAPH_TEST):
	@echo RUNNING SBG GRAPHS UNIT TESTS
	@cd $(UTEST_DIR) && ./graph-test
	@echo Done
	@echo BUILDING SBG GRAPHS SYSTEM TESTS
	@cd $(STEST_DIR) && $(MAKE) bin/test-sbg 
	@echo Done
	@echo RUNNING SBG GRAPHS SYSTEM TESTS
	@cd $(STEST_DIR) && $(MAKE) test-sbg 
	@echo Done
