# The Directories, Source, Includes, Objects, Binary 
SBG_DIR         := sbg
UTIL_DIR    := $(SBG_DIR)/util

# Sources
	UTIL_SRC := \
	$(UTIL_DIR)/defs.cpp \
    $(UTIL_DIR)/logger.cpp

# Objects
UTIL_OBJ=$(addprefix $(BUILD_DIR)/, $(UTIL_SRC:.cpp=.o))

create-folders::
	@mkdir -p $(BUILD_DIR)/$(UTIL_DIR)
